### ISSUE TITLE
Edwin Brady's whitespace

### ISSUE THREAD

**Issue by philipcraig** [Romejanic/Whitespace#2]
Please add something in the ReadMe that says how this differs from the already existing whitespace language (implementations collected at https://github.com/hostilefork/whitespacers/) designed by @edwinb

**Comment by MegaApuTurkUltra** [comment]
inb4 this gets silently closed like #1

**Comment by Romejanic** [comment]
I didn't think of this, thanks. [I've updated the readme](https://github.com/Romejanic/Whitespace/blob/master/README.md) in reference to this.
